import type { Contributor } from "../domain/types";

/** Simulated contributors — prototype data, not real people. */
export const demoContributors: Contributor[] = [
  {
    id: "c-01",
    displayName: "Ramesh Kumar",
    region: "Bundelkhand",
    state: "Madhya Pradesh",
    district: "Tikamgarh",
    language: "Hindi",
    dialect: "Bundeli",
    role: "knowledge_keeper",
    consentStatus: "granted",
    createdAt: "2026-02-04T09:10:00.000Z",
  },
  {
    id: "c-02",
    displayName: "Sunita Devi",
    region: "Bundelkhand",
    state: "Uttar Pradesh",
    district: "Jhansi",
    language: "Hindi",
    dialect: "Bundeli",
    role: "seed_keeper",
    consentStatus: "granted",
    createdAt: "2026-02-06T11:00:00.000Z",
  },
  {
    id: "c-03",
    displayName: "Mahesh Patil",
    region: "Vidarbha",
    state: "Maharashtra",
    district: "Yavatmal",
    language: "Marathi",
    dialect: "Varhadi",
    role: "farmer",
    consentStatus: "granted",
    createdAt: "2026-02-09T08:25:00.000Z",
  },
  {
    id: "c-04",
    displayName: "Lakshmi Reddy",
    region: "Telangana",
    state: "Telangana",
    district: "Warangal",
    language: "Telugu",
    dialect: null,
    role: "farmer",
    consentStatus: "granted",
    createdAt: "2026-02-11T14:45:00.000Z",
  },
  {
    id: "c-05",
    displayName: "Gurpreet Singh",
    region: "Malwa",
    state: "Punjab",
    district: "Bathinda",
    language: "Punjabi",
    dialect: "Malwai",
    role: "farmer",
    consentStatus: "granted",
    createdAt: "2026-02-13T07:30:00.000Z",
  },
  {
    id: "c-06",
    displayName: "Anita Barman",
    region: "Lower Assam",
    state: "Assam",
    district: "Nalbari",
    language: "Assamese",
    dialect: null,
    role: "traditional_practitioner",
    consentStatus: "granted",
    createdAt: "2026-02-15T10:05:00.000Z",
  },
  {
    id: "c-07",
    displayName: "Devendra Yadav",
    region: "Bundelkhand",
    state: "Madhya Pradesh",
    district: "Chhatarpur",
    language: "Hindi",
    dialect: "Bundeli",
    role: "livestock_specialist",
    consentStatus: "granted",
    createdAt: "2026-02-18T09:40:00.000Z",
  },
  {
    id: "c-08",
    displayName: "Kavitha Nair",
    region: "Malabar",
    state: "Kerala",
    district: "Wayanad",
    language: "Malayalam",
    dialect: null,
    role: "local_expert",
    consentStatus: "granted",
    createdAt: "2026-02-20T12:15:00.000Z",
  },
  {
    id: "c-09",
    displayName: "Bhim Rao Sable",
    region: "Marathwada",
    state: "Maharashtra",
    district: "Beed",
    language: "Marathi",
    dialect: null,
    role: "farmer",
    consentStatus: "granted",
    createdAt: "2026-02-22T06:50:00.000Z",
  },
  {
    id: "c-10",
    displayName: "Meena Kumari",
    region: "Mithila",
    state: "Bihar",
    district: "Madhubani",
    language: "Maithili",
    dialect: null,
    role: "seed_keeper",
    consentStatus: "granted",
    createdAt: "2026-02-25T08:00:00.000Z",
  },
  {
    id: "c-11",
    displayName: "Joseph Toppo",
    region: "Chotanagpur",
    state: "Jharkhand",
    district: "Gumla",
    language: "Hindi",
    dialect: "Nagpuri",
    role: "community_member",
    consentStatus: "granted",
    createdAt: "2026-03-01T13:20:00.000Z",
  },
  {
    id: "c-12",
    displayName: "Shanta Bai",
    region: "Vidarbha",
    state: "Maharashtra",
    district: "Akola",
    language: "Marathi",
    dialect: "Varhadi",
    role: "knowledge_keeper",
    consentStatus: "granted",
    createdAt: "2026-03-03T09:55:00.000Z",
  },
  {
    id: "c-13",
    displayName: "Imran Sheikh",
    region: "Saurashtra",
    state: "Gujarat",
    district: "Junagadh",
    language: "Gujarati",
    dialect: null,
    role: "farmer",
    consentStatus: "granted",
    createdAt: "2026-03-05T15:35:00.000Z",
  },
  {
    id: "c-14",
    displayName: "Rukmini Sahu",
    region: "Chhattisgarh Plains",
    state: "Chhattisgarh",
    district: "Dhamtari",
    language: "Chhattisgarhi",
    dialect: null,
    role: "farmer",
    consentStatus: "granted",
    createdAt: "2026-03-08T07:10:00.000Z",
  },
];

/** The contributor attributed to knowledge recorded during a demo session. */
export const demoSessionContributorId = "c-01";

export const contributorsById = new Map(demoContributors.map((c) => [c.id, c]));
