import type { KnowledgeRecord, KnowledgeType, SafetyStatus } from "../domain/types";

interface RecordSeed {
  id: string;
  title: string;
  transcript: string;
  transcriptNote?: string;
  language: string;
  dialect?: string;
  type: KnowledgeType;
  crop?: string;
  animal?: string;
  problem?: string;
  practice?: string;
  method?: string;
  season?: string;
  region: string;
  district?: string;
  context?: string;
  contributorId: string;
  safety?: SafetyStatus;
  safetyNote?: string;
  createdAt: string;
  hasAudio?: boolean;
}

function toRecord(seed: RecordSeed): KnowledgeRecord {
  return {
    id: seed.id,
    title: seed.title,
    transcript: seed.transcript,
    transcriptNote: seed.transcriptNote ?? null,
    originalLanguage: seed.language,
    dialect: seed.dialect ?? null,
    knowledgeType: seed.type,
    crop: seed.crop ?? null,
    animal: seed.animal ?? null,
    problem: seed.problem ?? null,
    practice: seed.practice ?? null,
    method: seed.method ?? null,
    season: seed.season ?? null,
    region: seed.region,
    district: seed.district ?? null,
    context: seed.context ?? null,
    // Demo audio is not shipped as media files; the player exposes an honest
    // "audio unavailable" state while keeping the transcript accessible.
    audioUrl: seed.hasAudio === false ? null : `demo://audio/${seed.id}/original.webm`,
    contributorId: seed.contributorId,
    visibility: "public",
    sourceType: "voice_recording",
    status: "published",
    verificationStatus: "community_reported",
    safetyStatus: seed.safety ?? "not_assessed",
    safetyNote: seed.safetyNote ?? null,
    embedding: null,
    createdAt: seed.createdAt,
    updatedAt: seed.createdAt,
    isDemo: true,
  };
}

const seeds: RecordSeed[] = [
  {
    id: "k-01",
    title: "Neem-based chilli pest management",
    transcript:
      "Mirchi mein jab keeda lagta hai to hum neem ki nimboli ko raat bhar paani mein bhigo dete hain, subah chhan kar spray karte hain. Shaam ko chhidkav karna theek rehta hai.",
    transcriptNote: "Hindi (Bundeli) — transliterated as spoken.",
    language: "Hindi",
    dialect: "Bundeli",
    type: "pest_management",
    crop: "Chilli",
    problem: "Pest pressure",
    practice: "Community-reported neem seed preparation",
    method: "Neem seed kernels soaked overnight, strained, sprayed in the evening",
    season: "Vegetative stage",
    region: "Bundelkhand",
    district: "Tikamgarh",
    context: "Smallholder cultivation, rainfed plots",
    contributorId: "c-01",
    safety: "caution",
    safetyNote: "Preparation strength varies. Effectiveness and safety may vary by context.",
    createdAt: "2026-03-12T06:20:00.000Z",
  },
  {
    id: "k-02",
    title: "Local chilli pest practice with ash and buttermilk",
    transcript:
      "Mirchi ke patton par jab chhote keede dikhte hain, hum raakh aur khatti chaas milakar chhidakte hain. Teen din baad phir se karte hain.",
    language: "Hindi",
    dialect: "Bundeli",
    type: "pest_management",
    crop: "Chilli",
    problem: "Pest pressure",
    practice: "Wood ash and soured buttermilk spray",
    method: "Sieved wood ash mixed with soured buttermilk, repeated after three days",
    season: "Vegetative stage",
    region: "Bundelkhand",
    district: "Jhansi",
    context: "Kitchen-garden and small plot cultivation",
    contributorId: "c-02",
    safety: "caution",
    createdAt: "2026-03-14T05:40:00.000Z",
  },
  {
    id: "k-03",
    title: "Farmer-reported chilli preparation method",
    transcript:
      "Mirchi la kida lagla tar amhi neem pala ani lasun ekatra vatun paani madhe takto, ani sakali favarni karto.",
    transcriptNote: "Marathi (Varhadi) — transliterated as spoken.",
    language: "Marathi",
    dialect: "Varhadi",
    type: "pest_management",
    crop: "Chilli",
    problem: "Pest pressure",
    practice: "Neem leaf and garlic extract",
    method: "Neem leaves and garlic ground together, steeped, sprayed in the morning",
    season: "Flowering stage",
    region: "Vidarbha",
    district: "Yavatmal",
    context: "Rainfed chilli, one acre",
    contributorId: "c-03",
    createdAt: "2026-03-16T04:55:00.000Z",
  },
  {
    id: "k-04",
    title: "Ash-layer seed storage for pulses",
    transcript:
      "Beej ko ghar par rakhne ke liye hum mitti ke matke mein raakh ki tah lagakar rakhte hain, upar neem ke patte rakh dete hain.",
    language: "Hindi",
    type: "seed_practice",
    crop: "Pulses",
    problem: "Storage pests",
    practice: "Ash-layered earthen pot storage",
    method: "Alternating layers of dry ash and seed in an earthen pot, sealed with cloth",
    season: "Post-harvest",
    region: "Mithila",
    district: "Madhubani",
    context: "Household seed saving",
    contributorId: "c-10",
    createdAt: "2026-03-02T10:10:00.000Z",
  },
  {
    id: "k-05",
    title: "Paddy seed selection by water float test",
    transcript:
      "Dhaan ke beej ko namak ke paani mein daal kar dekhte hain. Jo beej upar taire, use hata dete hain. Neeche baithne wale beej hi bote hain.",
    language: "Hindi",
    type: "seed_practice",
    crop: "Paddy",
    problem: "Poor germination",
    practice: "Salt-water float separation of seed",
    method: "Seed placed in salt water; floating seed discarded before sowing",
    season: "Pre-sowing",
    region: "Chhattisgarh Plains",
    district: "Dhamtari",
    context: "Transplanted paddy, canal irrigated",
    contributorId: "c-14",
    createdAt: "2026-02-27T05:25:00.000Z",
  },
  {
    id: "k-06",
    title: "Alternate wetting and drying in transplanted paddy",
    transcript:
      "Dhaan mein hamesha paani bhara rakhne ki jarurat nahin. Khet sukhne ke baad hi dobara paani dete hain, isse jad majboot hoti hai.",
    language: "Hindi",
    type: "irrigation_practice",
    crop: "Paddy",
    problem: "Water scarcity",
    practice: "Alternate wetting and drying",
    method: "Field allowed to drain until hairline cracks appear before re-irrigation",
    season: "Tillering to panicle initiation",
    region: "Chhattisgarh Plains",
    contributorId: "c-14",
    createdAt: "2026-02-28T05:25:00.000Z",
  },
  {
    id: "k-07",
    title: "Wheat sowing depth after late rains",
    transcript:
      "Baarish der se hone par gehun ko thoda gehra bona padta hai, warna jamav kam hota hai. Do inch tak theek rehta hai.",
    language: "Punjabi",
    dialect: "Malwai",
    type: "crop_practice",
    crop: "Wheat",
    problem: "Uneven germination",
    practice: "Adjusted sowing depth for late-sown wheat",
    season: "Rabi sowing",
    region: "Malwa",
    district: "Bathinda",
    context: "Irrigated wheat after paddy",
    contributorId: "c-05",
    createdAt: "2026-02-19T07:00:00.000Z",
  },
  {
    id: "k-08",
    title: "Mustard intercropping to reduce aphid damage",
    transcript:
      "Gehun ke saath sarson ki ek line laga dete hain. Keeda pehle sarson par aata hai, gehun bach jata hai.",
    language: "Hindi",
    type: "pest_management",
    crop: "Mustard",
    problem: "Aphid pressure",
    practice: "Border and strip intercropping",
    season: "Rabi",
    region: "Bundelkhand",
    contributorId: "c-01",
    createdAt: "2026-02-21T06:30:00.000Z",
  },
  {
    id: "k-09",
    title: "Cattle feed storage during monsoon",
    transcript:
      "Barsat mein bhusa kharab ho jata hai. Hum bhusa ko bans ke machan par rakhte hain aur neeche raakh daal dete hain.",
    language: "Hindi",
    dialect: "Bundeli",
    type: "storage_practice",
    animal: "Cattle",
    problem: "Fodder spoilage",
    practice: "Raised bamboo platform storage",
    season: "Monsoon",
    region: "Bundelkhand",
    district: "Chhatarpur",
    contributorId: "c-07",
    createdAt: "2026-02-24T08:45:00.000Z",
  },
  {
    id: "k-10",
    title: "Mineral lick and shade routine for dairy cattle in summer",
    transcript:
      "Garmi mein gaay kam khati hai. Dopahar mein chhaya aur namak ki dali rakhte hain, paani do baar badalte hain.",
    language: "Hindi",
    type: "livestock_practice",
    animal: "Dairy cattle",
    problem: "Heat stress",
    practice: "Shade, salt lick and water refresh routine",
    season: "Summer",
    region: "Bundelkhand",
    contributorId: "c-07",
    safety: "caution",
    safetyNote: "This record is not veterinary advice. Consult a veterinarian for animal health.",
    createdAt: "2026-03-04T09:15:00.000Z",
  },
  {
    id: "k-11",
    title: "Green manure with dhaincha before paddy",
    transcript:
      "Dhaan se pehle dhaincha bo dete hain aur phool aane se pehle khet mein hi mila dete hain. Mitti narm ho jati hai.",
    language: "Hindi",
    type: "soil_practice",
    crop: "Paddy",
    problem: "Low soil fertility",
    practice: "Green manure incorporation",
    season: "Pre-kharif",
    region: "Mithila",
    contributorId: "c-10",
    createdAt: "2026-03-06T06:05:00.000Z",
  },
  {
    id: "k-12",
    title: "Cow-dung slurry seed treatment",
    transcript:
      "Beej ko bone se pehle gobar aur paani ke ghol mein bhigo kar chhaya mein sukhate hain.",
    language: "Chhattisgarhi",
    type: "seed_practice",
    crop: "Paddy",
    practice: "Slurry seed coating before sowing",
    season: "Pre-sowing",
    region: "Chhattisgarh Plains",
    contributorId: "c-14",
    createdAt: "2026-03-07T05:00:00.000Z",
  },
  {
    id: "k-13",
    title: "Trench mulching in rainfed cotton",
    transcript:
      "Kapus madhe olawa tikawnyasathi amhi don olinchya madhe kachra ani paala takto. Jamin jast vel ola rahto.",
    language: "Marathi",
    dialect: "Varhadi",
    type: "soil_practice",
    crop: "Cotton",
    problem: "Moisture loss",
    practice: "In-row residue mulching",
    season: "Kharif",
    region: "Vidarbha",
    district: "Akola",
    contributorId: "c-12",
    createdAt: "2026-03-09T04:35:00.000Z",
  },
  {
    id: "k-14",
    title: "Pheromone-free yellow sticky traps from local material",
    transcript:
      "Peele rang ke tin ke tukde par chikna tel laga kar khet mein lagate hain, safed makkhi chipak jati hai.",
    language: "Hindi",
    type: "pest_management",
    crop: "Vegetables",
    problem: "Whitefly pressure",
    practice: "Locally made yellow sticky traps",
    season: "Vegetative stage",
    region: "Bundelkhand",
    contributorId: "c-02",
    createdAt: "2026-03-10T07:20:00.000Z",
  },
  {
    id: "k-15",
    title: "Neem-cake application in groundnut",
    transcript:
      "Mungfali mein neem khali dalne se jameen ke keede kam hote hain, aisa humne dekha hai.",
    language: "Gujarati",
    type: "pest_management",
    crop: "Groundnut",
    problem: "Soil-borne pests",
    practice: "Neem cake soil application",
    season: "Sowing",
    region: "Saurashtra",
    district: "Junagadh",
    contributorId: "c-13",
    createdAt: "2026-03-11T06:45:00.000Z",
  },
  {
    id: "k-16",
    title: "Turmeric boiling and drying practice",
    transcript:
      "Haldi ko ubaal kar chhaya mein sukhate hain to rang accha aata hai aur bhandaran mein kharab nahin hoti.",
    language: "Telugu",
    type: "storage_practice",
    crop: "Turmeric",
    problem: "Post-harvest quality loss",
    practice: "Boil-and-shade-dry curing",
    season: "Post-harvest",
    region: "Telangana",
    district: "Warangal",
    contributorId: "c-04",
    createdAt: "2026-02-26T09:30:00.000Z",
  },
  {
    id: "k-17",
    title: "Tank silt application to sandy plots",
    transcript:
      "Cheruvu lo undhe matti ni polam lo vesthe, neeru ekkuva sepu untundi. Prathi renduu samvatsarala ki okasari chesthaam.",
    language: "Telugu",
    type: "soil_practice",
    problem: "Poor water holding capacity",
    practice: "Tank silt spreading",
    season: "Summer, before monsoon",
    region: "Telangana",
    contributorId: "c-04",
    createdAt: "2026-02-23T08:05:00.000Z",
  },
  {
    id: "k-18",
    title: "Coconut husk burial for moisture retention",
    transcript:
      "Thengin thondu kuzhiyil ittu manninu adiyil vaykkum. Vellam kurachu divasam koodi nilkkum.",
    language: "Malayalam",
    type: "irrigation_practice",
    crop: "Coconut",
    problem: "Moisture loss",
    practice: "Husk burial in basins",
    season: "Pre-summer",
    region: "Malabar",
    district: "Wayanad",
    contributorId: "c-08",
    createdAt: "2026-03-13T10:50:00.000Z",
  },
  {
    id: "k-19",
    title: "Rice-bran and jaggery ferment as a soil input",
    transcript:
      "Chawal ka chokar, gud aur paani milakar kuch din rakhte hain, phir patla karke khet mein dete hain. Kuch logon ko fayda hua, kuch ko nahin.",
    language: "Hindi",
    type: "soil_practice",
    crop: "Vegetables",
    problem: "Weak plant growth",
    practice: "Fermented bran and jaggery solution",
    method: "Fermented 7 days, diluted before field application",
    season: "Vegetative stage",
    region: "Chotanagpur",
    district: "Gumla",
    context: "Mixed vegetable plots",
    contributorId: "c-11",
    safety: "caution",
    safetyNote: "Community reports disagree on this practice. Results vary by preparation.",
    createdAt: "2026-03-15T11:25:00.000Z",
  },
  {
    id: "k-20",
    title: "Goat shed bedding change in wet season",
    transcript:
      "Barsat mein bakri ke baade mein sukhi ghaas roz badalte hain, warna paon mein dikkat hoti hai.",
    language: "Hindi",
    type: "livestock_practice",
    animal: "Goat",
    problem: "Wet bedding and hoof problems",
    practice: "Daily dry bedding replacement",
    season: "Monsoon",
    region: "Chotanagpur",
    contributorId: "c-11",
    safety: "caution",
    safetyNote: "This record is not veterinary advice.",
    createdAt: "2026-03-17T08:10:00.000Z",
  },
  {
    id: "k-21",
    title: "Seed drying on cloth before storage",
    transcript:
      "Beej ko seedha zameen par nahin sukhate, kapde par sukhate hain. Isse nami nahin rehti.",
    language: "Maithili",
    type: "seed_practice",
    problem: "Seed moisture",
    practice: "Cloth-surface shade drying",
    season: "Post-harvest",
    region: "Mithila",
    contributorId: "c-10",
    createdAt: "2026-02-17T07:40:00.000Z",
  },
  {
    id: "k-22",
    title: "Bund planting of pigeon pea around paddy",
    transcript: "Dhaan ke medh par arhar laga dete hain, do fasal ho jati hai aur medh majboot rehti hai.",
    language: "Hindi",
    type: "crop_practice",
    crop: "Pigeon pea",
    practice: "Bund cropping",
    season: "Kharif",
    region: "Chhattisgarh Plains",
    contributorId: "c-14",
    createdAt: "2026-02-16T06:15:00.000Z",
  },
  {
    id: "k-23",
    title: "Early morning irrigation to reduce wheat heat stress",
    transcript:
      "Garmi jaldi aa jaye to gehun ko subah subah paani dete hain, dopahar mein nahin.",
    language: "Punjabi",
    type: "irrigation_practice",
    crop: "Wheat",
    problem: "Terminal heat stress",
    practice: "Timing irrigation to early morning",
    season: "Late rabi",
    region: "Malwa",
    contributorId: "c-05",
    createdAt: "2026-03-18T05:20:00.000Z",
  },
  {
    id: "k-24",
    title: "Sorghum stubble grazing rotation",
    transcript:
      "Jowar kaatne ke baad janwar ko ek hi jagah nahin chhodte, hisson mein charate hain.",
    language: "Marathi",
    type: "livestock_practice",
    animal: "Cattle",
    crop: "Sorghum",
    practice: "Sectioned stubble grazing",
    season: "Post-harvest",
    region: "Marathwada",
    district: "Beed",
    contributorId: "c-09",
    createdAt: "2026-03-19T06:55:00.000Z",
  },
  {
    id: "k-25",
    title: "Onion storage in ventilated bamboo racks",
    transcript: "Kanda bambuchya rack var thevto, hawa khelti rahili ki kanda sadat nahi.",
    language: "Marathi",
    type: "storage_practice",
    crop: "Onion",
    problem: "Storage rot",
    practice: "Ventilated rack storage",
    season: "Post-harvest",
    region: "Marathwada",
    contributorId: "c-09",
    createdAt: "2026-03-20T07:35:00.000Z",
  },
  {
    id: "k-26",
    title: "Rice husk ash in vegetable nursery beds",
    transcript:
      "Nursery mein dhaan ki bhusi ki raakh milate hain, choti paudh jaldi nahin marti.",
    language: "Assamese",
    type: "soil_practice",
    crop: "Vegetables",
    problem: "Seedling damping off",
    practice: "Husk ash in nursery beds",
    season: "Nursery stage",
    region: "Lower Assam",
    district: "Nalbari",
    contributorId: "c-06",
    safety: "caution",
    createdAt: "2026-03-21T09:05:00.000Z",
  },
  {
    id: "k-27",
    title: "Betel vine shade management",
    transcript: "Paan ke bagan mein garmi mein upar se chhaya badhate hain, patta jalta nahin.",
    language: "Assamese",
    type: "crop_practice",
    crop: "Betel vine",
    problem: "Leaf scorching",
    practice: "Seasonal shade adjustment",
    season: "Summer",
    region: "Lower Assam",
    contributorId: "c-06",
    createdAt: "2026-03-22T08:30:00.000Z",
  },
  {
    id: "k-28",
    title: "Mixed millet sowing in shallow soils",
    transcript:
      "Patli jameen mein akela bajra nahin bote, saath mein kodo aur kutki mila dete hain.",
    language: "Hindi",
    dialect: "Nagpuri",
    type: "seasonal_practice",
    crop: "Millets",
    problem: "Crop failure risk on shallow soils",
    practice: "Mixed millet sowing",
    season: "Kharif",
    region: "Chotanagpur",
    contributorId: "c-11",
    createdAt: "2026-03-23T06:40:00.000Z",
  },
  {
    id: "k-29",
    title: "Reading pre-monsoon wind for sowing time",
    transcript:
      "Jab purva hawa chalne lagti hai aur cheenti ande uthati hain, tab bona shuru karte hain.",
    language: "Hindi",
    dialect: "Bundeli",
    type: "seasonal_practice",
    practice: "Local indicators for sowing window",
    season: "Pre-monsoon",
    region: "Bundelkhand",
    contributorId: "c-01",
    createdAt: "2026-03-24T05:50:00.000Z",
  },
  {
    id: "k-30",
    title: "Garlic and chilli extract for storage grain",
    transcript:
      "Anaj ki kothi mein lehsun aur sukhi mirchi rakh dete hain, keeda kam lagta hai.",
    language: "Gujarati",
    type: "storage_practice",
    crop: "Grain",
    problem: "Storage insects",
    practice: "Garlic and dried chilli in grain bins",
    season: "Post-harvest",
    region: "Saurashtra",
    contributorId: "c-13",
    safety: "caution",
    createdAt: "2026-03-25T07:15:00.000Z",
  },
];

export const demoKnowledgeRecords: KnowledgeRecord[] = seeds.map(toRecord);

/** Records that express the same practice in different words. */
export const demoPracticeClusters: Record<string, string[]> = {
  "chilli-pest": ["k-01", "k-02", "k-03"],
};
